controller_manager:
  ros__parameters:
    update_rate: 1000
    # Publish all joint states -----------------------------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      #FL_hip_joint:
      #type: unitree_legged_control/UnitreeJointController

      #FL_hip_joint:
      #ros__parameters:
    # FL Controllers ---------------------------------------
    #joint: FL_hip_joint
    #pid: {p: 100.0, i: 0.0, d: 5.0}


