controller_manager:
  ros__parameters:
    update_rate: 1000
    # Publish all joint states -----------------------------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    a1_dog_controller:
      type: unitree_legged_control/UnitreeJointController

a1_dog_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
    interface_name: velocity    


